### ISSUE TITLE
ArrayIndexOutOfBoundsException in BinarySearch >> InfiniteArray 

### ISSUE THREAD

**Issue by oseamiya** [kunal-kushwaha/DSA-Bootcamp-Java#645]
In <a href="https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java"> this code </a> of Infinite Array from BinarySearch lecture, 

When we try to get target element more than half size of the array (like 100 or 130), it will throw ArrayIndexOutOfBoundsException like : 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 11
	at Main.ans(InfiniteArray.java:17)
	at Main.main(InfiniteArray.java:8)
```
It is because `end` variable in `ans` method crosses/exceeds more than size of array.

**Comment by brawlon** [comment]
I had the same doubt but apparently 
<img width="940" alt="Screenshot 2022-05-12 at 1 09 49 PM" src="https://user-images.githubusercontent.com/27919652/168017965-412374c9-f68a-44b5-a9ff-845b46625e06.png">
So yes, we do not consider this a bug as we are imagining an infinite array with no limit of the elements

**Comment by brawlon** [comment]
You can check PR #565

**Comment by nesarptr** [comment]
> In [ this code ](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java) of Infinite Array from BinarySearch lecture,
> 
> When we try to get target element more than half size of the array (like 100 or 130), it will throw ArrayIndexOutOfBoundsException like :
> 
> ```
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 11
> 	at Main.ans(InfiniteArray.java:17)
> 	at Main.main(InfiniteArray.java:8)
> ```
> 
> It is because when executing `while(target > arr[end])`, as end will be greater than size of the array, it will throw this error.
> 
> Or, Do we not consider this a bug as we are imagining an infinite array with no limit of the elements ?

Since this is an infinite array there is no chance of getting an exception like this, if you still get it, that means the array has a limit and it is not an infinite array :)

**Comment by atha2810** [comment]
> In [ this code ](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java) of Infinite Array from BinarySearch lecture,
> 
> When we try to get target element more than half size of the array (like 100 or 130), it will throw ArrayIndexOutOfBoundsException like :
> 
> ```
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 11
> 	at Main.ans(InfiniteArray.java:17)
> 	at Main.main(InfiniteArray.java:8)
> ```
> 
> It is because when executing `while(target > arr[end])`, as end will be greater than size of the array, it will throw this error.
> 
> Or, Do we not consider this a bug as we are imagining an infinite array with no limit of the elements ?

it will work when array is infinite

**Comment by Arsh164** [comment]
This is the code which works if the Array Index Out of Bounds exception is happend :

`public class BinarySearchInfiniteArray {
    public static void main(String[] args) {
        int[] array={3,5,7,9,10,90,100,130,140,160,170};
        int target=10;
        int ans=infinitesearch(array,target);
        System.out.println(ans);
    }

    public static int infinitesearch(int[] arr, int target) {
        int i = 0;
        int f = 0;
        int l = 0;
        // Using try catch to for catching Array Index out of index exception
        try {

            while (true) {
                f = l + 1;
                l = l + 2 ^ i;
                while (f <= l) {

                    int mid = f + (l - f) / 2;
                    if (arr[mid] < target) {
                        f = mid + 1;

                    } else if (arr[mid] > target) {
                        l = mid - 1;
                    } else {
                        return mid;
                    }
                    i++;
                }
            }

        } catch (ArrayIndexOutOfBoundsException exception) {
            //Resolving it to find the last index of array
            int temp = f;
            boolean error = false;
            int mid = 0;
            while (!error) // Till the last index is not found
            {
                //Uisng Binary Search approach to find the last index of array
                try {
                    mid = f + (f - l) / 2;
                    f = mid;
                    if (f == l) //Point where the last array is found
                    {
                        error = true;
                    }
                } catch (ArrayIndexOutOfBoundsException exception1) //Exception When mid is out of bounds
                {
                    l = mid;
                }
            }
            //Last index of array is Found 
            f = temp;
            while (f <= l) {

                mid = f + (l - f) / 2;
                if (arr[mid] < target) {
                    f = mid + 1;

                } else if (arr[mid] > target) {
                    l = mid - 1;
                } else {
                    return mid;
                }


            }

        }
        return -1;// If target element is not present
    }
}
`

Feel free to message regarding the code doubts.
